name: BuildAndTestOnEveryPush.yml

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build on windows-latest
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: dotnet build Frends.Test.TestWorkflow.sln
    
    - name: Test
      run: dotnet test Frends.Test.TestWorkflow.sln
      
    - name: Pack release version of task
      run: dotnet pack Frends.Test.TestWorkflow\Frends.Test.TestWorkflow.csproj --configuration Release --include-source
